name = "ndigirigijohn/tokenwell-sc"
version = "0.0.0"
compiler = "v1.1.15"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'ndigirigijohn/tokenwell-sc'"

[repository]
user = "ndigirigijohn"
project = "tokenwell-sc"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config]
